# Copyright (c) Karagatan LLC.
# SPDX-License-Identifier: BUSL-1.1

FROM codeallergy/ubuntu-golang as builder

ARG VERSION
ARG BUILD

WORKDIR /go/src/go.arpabet.com/template
ADD . .

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
    autoconf automake libtool curl make g++ unzip

RUN bash .github/scripts/install-protoc.sh 3.20.3
RUN make deps
RUN make

CMD ["cat", "template"]

